FROM python:3.11-slim

WORKDIR /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY pyproject.toml .
RUN pip install -U pip && pip install -e .[test]

COPY . .
RUN chmod +x /app/scripts/*.sh